version: "3.8"
services:
    studio-frontend:
        build:
            context: .
            dockerfile: Dockerfile
        # container_name: dahlia.studio-frontend
        image: theun/studio-frontend
        volumes:
            - .:/studio-frontend
            - ~/container_only_node_modules:/studio-frontend/node_modules
        ports:
            - "18011:18011"
            - "9229:9229"
        networks:
            smtnet:

networks:
  smtnet:
    external: true

volumes:
  container_only_node_modules:
